#config.yaml for mutect2.snakefile
#Anna Hoge
#Template made October 18th, 2019
#Ha Lab
#Fred Hutchinson Cancer Research Center

#SELECT PANEL OF NORMALS IN VCF.GZ FORMAT OR "null"
panel_of_normals: null
#panel_of_normals: "/path/to/your/panel_of_normals.vcf.gz"

#reference genome for mutect2 call, with index files in same folder as .fa file
reference_genome:
    /path/to/genome.fa

#with index files in same folder as .vcf.gz file
mutect2_germline_resource:
    /path/to/somatic-hg38_af-only-gnomad.hg38.vcf.gz
    #/path/to/af-only-gnomad.raw.sites.b37_with_chr.vcf.gz

#used for get_pileup_summaries
known_polymorphic_sites:
    /path/to/somatic-hg38_small_exac_common_3.hg38.vcf.gz
    #/path/to/small_exac_common_3_b37_with_chr.vcf.gz

#used for running mutect2 by interval
chromosomes: ['chr1','chr2','chr3','chr4','chr5','chr6','chr7','chr8','chr9','chr10','chr11','chr12','chr13','chr14','chr15','chr16','chr17','chr18','chr19','chr20','chr21','chr22','chrX', 'chrY']

#tools used.  these must be module loaded before running snakemake. see snakefile for load commands
gatk: /path/to/gatk
java: /path/to/java
tabix: /path/to/tabix
picard_jar: /path/to/picard.jar